---
AWSTemplateFormatVersion: '2010-09-09'
Description: MongoDB Atlas AWS CloudFormation Quickstart for MongoDB::Atlas::Table
Parameters:
  PublicKey:
    Description: "Your MongoDB Cloud Public API Key"
    Type: String
    Default: ""
  PrivateKey:
    Description: "Your MongoDB Cloud Private API Key"
    Type: String
    Default: ""
  OrgId:
    Description: "Your MongoDB Cloud Private OrgId, optional"
    Type: String
    Default: ""
  ProjectId:
    Description: "A MongoDB Atlas Project for your Table"
    Type: String
    Default: ""
  TableName:
    Description: Name of the Table as it appears in Atlas. Once the table is created, its name cannot be changed.
    Type: String
    Default: ""
  ClusterName:
    Description: Name of the Table as it appears in Atlas. Once the table is created, its name cannot be changed.
    Type: String
    Default: "Quickstart"
  RegionName:
    Default: us-east-1
    Description: The AWS Region where the Atlas DB Cluster will run.
    Type: String
    AllowedValues:
    - "us-east-1"
    - "us-east-2"
    - "ca-central-1"
    - "us-west-1"
    - "us-west-2"
    - "sa-east-1"
    - "ap-south-1"
    - "ap-east-2"
    - "ap-southeast-1"
    - "ap-southeast-2"
    - "ap-northeast-1"
    - "ap-northeast-2"
    - "eu-central-1"
    - "eu-west-1"
    - "eu-north-1"
    - "eu-west-1"
    - "eu-west-2"
    - "eu-west-3"
    - "eu-south-1"
    - "me-south-1"
    - "af-south-1"
Resources:
  AtlasApiKeySecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub "${AWS::StackName}-ApiKey-Secret"
      Description: This secret has a hardcoded password in SecretString, how can i make this optional?
      #
      # { "PublicKey" : "xxx", "PrivateKey", "yyy", "OrgId": "zzz" }
      #
      SecretString: !Join ['', ['{"PublicKey":"', !Ref "PublicKey",'", "PrivateKey":"', !Ref "PrivateKey", '", "OrgId":"', !Ref "OrgId", '"}'] ]
      Tags:
      - Key: mongodb-atlas-quickstart
        Value: !Sub "${AWS::StackName}"
  AtlasTable:
    Type: MongoDB::Atlas::Table
    Properties:
      ProjectId: !Ref "ProjectId" 
      PublicApiKey: !Join [ "", [ "{{resolve:secretsmanager:", !Ref "AtlasApiKeySecret", ":SecretString:PublicKey}}" ] ]
      PrivateApiKey: !Join [ "", [ "{{resolve:secretsmanager:", !Ref "AtlasApiKeySecret", ":SecretString:PrivateKey}}" ] ]
      TableName: !Sub "${AWS::StackName}"
      ClusterName: !Ref "ClusterName"
      RegionName: !Ref "RegionName"

Outputs:
  AtlasTable:
    Description: "Info on your Atlas table"
    Value: !Ref AtlasTable
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName","AtlasTable" ] ]
  ConnectionString:
    Description: "Hostname for mongodb+srv:// connection string"
    Value: !GetAtt "AtlasTable.ConnectionStringsStandardSrv"
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName","TableSrvAddress" ] ]

