


on: [delete]
  #  release:
#types: [created]

name: atlas-cfn-deploy 

jobs:
  clean-cf:
    name: Prepare CF for testing. Cleanup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      
      - name: Cleanup ENV for current branch
        uses: ./.github/actions/atlas-cfn-deploy
        with:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

#on: 
#  workflow_dispatch:
#jobs:
#  atlas-cfn-deploy:
#    name: atlas-cfn-deploy
#    runs-on: ubuntu-latest
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v2.3.1
#    - name: call-cfn-deploy 
#      uses: actions/atlas-cfn-deploy
#      env:
#        AWS_REGION: us-east-2
#        STACK_NAME: cfn-deploy
#        TEMPLATE_FILE: ec2.yml
#        PARAMETERS_FILE: parameter.json
#        CAPABLITIES: CAPABILITY_IAM
#        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
#        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
#
