name: Deploy MongoDB Atlas CFN Resources
on:
  workflow_dispatch:
    inputs:
      region: 
        description: "AWS region"
        default: "us-east-1"
        required: true

jobs:
  atlas-cfn-deploy:
    name: atlas-cfn-deploy
    runs-on: ubuntu:20.04
    env:
      CAPABLITIES: CAPABILITY_IAM
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_REGION: ${{ github.event.inputs.region }}
    steps:
    - uses: actions/checkout@v2.3.1
      name: pull code
    - name: Run the atlas-cfn-deploy custom action.
      uses: ./.github/actions/atlas-cfn-deploy
      with:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_REGION: ${{ github.event.inputs.region }}
