name: check-copyright
on:
  push:
    branches: [ "master" , "INT**"]
  pull_request:
    branches: [ "master", "INT**" ]
jobs:
  lint-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: check copyright
        run: ../../build/ci/check-licence.sh
        shell: bash
