name: Deploy MongoDB Atlas CloudFormation Resources 
on:
  workflow_dispatch:
    inputs:
      region: 
        description: "AWS region"
        default: "us-east-1"
        required: true
jobs:
  atlas-cfn-deploy:
    name: atlas-cfn-deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
      name: pull code
    - name: echo env
      run: |
        echo "#############################################################"
        env
        echo "#############################################################"
    - name: Run the atlas-cfn-deploy custom action.
      uses: ./.github/actions/atlas-cfn-deploy
      with:
        CAPABLITIES: CAPABILITY_IAM
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION_INPUT: ${{ github.event.inputs.region }}
        AWS_REGION_SECRET: ${{ secrets.AWS_REGION }}
        XXINPUTS: $${{ github.event.inputs }}
