name: Deploy MongoDB Atlas CloudFormation Resources 
on:
  workflow_dispatch:
    inputs:
      region: 
        description: "AWS region"
        default: "us-east-1"
        required: true
      projectName:
        description: "Name"
        default: "atlas-cfn-quickstart"
        required: true
      instanceSize:
        description: "Instance size, defaults to M10"
        default: "M10"
        required: true
      databaseUsername:
        description: "Database username"
        default: "atlas"
        required: true
      databasePassword:
        description: "Database password"
        default: "atlas123"
        required: true
jobs:
  atlas-cfn-deploy:
    name: atlas-cfn-deploy
    #runs-on: ubuntu-20.04
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
      name: pull code
    - name: echo env
      run: |
        echo "#############################################################"
        env
        echo "#############################################################"
    - name: Run the atlas-cfn-deploy custom action.
      if: ${{ github.event.inputs.deployResources }} == "yes"
      uses: ./.github/actions/atlas-cfn-deploy
      with:
        CAPABLITIES: CAPABILITY_IAM
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION_INPUT: ${{ github.event.inputs.region }}
        AWS_REGION_SECRET: ${{ secrets.AWS_REGION }}
        XXINPUTS: $${{ github.event.inputs }}
    - name: Deploy wrap up
      run: |
        echo "Wrap up"
