name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
- name: Load runner information
  # You may pin to the exact commit or the version.
  # uses: devops-actions/load-runner-info@2722eef3f2147e230b89e4469dd664c10de13f24
  uses: devops-actions/load-runner-info@v1.0.9
  with:
    # Slug of the organization to analyze.
    organization: 
    # Slug of the repository to analyze.
    repo: # optional
    # Access token to use for analysis with either admin:org or repo owner if you run it against a repo
    accessToken: 
    
